config/routes.rb
Rails.application.routes.draw do
  resources :growth_calculators do
    collection do
      get :population
    end
  end

end

app/models/growth_calculator.rb
class GrowthCalculator < ActiveRecord::Base


  # Formula for population at a given time is initial_population * exp(rate * time)
  def self.calculate_population_table(starting_population = 0,time_frame = 0,growth_rate = 0)
    Rails.logger.debug "Inputs: #{starting_population} #{time_frame} #{growth_rate}"
    population = []
    (0..time_frame).each do |t|
      population << starting_population * Math.exp(growth_rate * t)
    end
    return population # the word return is optional - could just put population
  end

  def calculate_population_table
    return self.class.calculate_population_table(self.starting_population,self.time_frame,self.growth_rate)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/growth_calculators_controller.rb
class GrowthCalculatorsController < ApplicationController
  before_action :set_growth_calculator, only: [:show, :edit, :update, :destroy]

  # GET /growth_calculators
  # GET /growth_calculators.json
  def index
    @growth_calculators = GrowthCalculator.all
  end

  # GET /growth_calculators/1
  # GET /growth_calculators/1.json
  def show
    @population_array = @growth_calculator.calculate_population_table
  end

  # GET /growth_calculators/new
  def new
    @growth_calculator = GrowthCalculator.new
  end

  # GET /growth_calculators/1/edit
  def edit
  end

  # POST /growth_calculators
  # POST /growth_calculators.json
  def create
    @growth_calculator = GrowthCalculator.new(growth_calculator_params)

    respond_to do |format|
      if @growth_calculator.save
        format.html { redirect_to @growth_calculator, notice: 'Growth calculator was successfully created.' }
        format.json { render :show, status: :created, location: @growth_calculator }
      else
        format.html { render :new }
        format.json { render json: @growth_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /growth_calculators/1
  # PATCH/PUT /growth_calculators/1.json
  def update
    respond_to do |format|
      if @growth_calculator.update(growth_calculator_params)
        format.html { redirect_to @growth_calculator, notice: 'Growth calculator was successfully updated.' }
        format.json { render :show, status: :ok, location: @growth_calculator }
      else
        format.html { render :edit }
        format.json { render json: @growth_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /growth_calculators/1
  # DELETE /growth_calculators/1.json
  def destroy
    @growth_calculator.destroy
    respond_to do |format|
      format.html { redirect_to growth_calculators_url, notice: 'Growth calculator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def population
    rate = params[:rate]
    time = params[:time]
    initial_population = params[:pop]
    @population_array = GrowthCalculator.calculate_population_table(initial_population.to_i, time.to_i, rate.to_f)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_growth_calculator
      @growth_calculator = GrowthCalculator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def growth_calculator_params
      params.require(:growth_calculator).permit(:starting_population, :growth_rate, :time_frame)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/growth_calculators_helper.rb
module GrowthCalculatorsHelper
end

app/views/growth_calculators/_form.html.erb
<%= form_for(@growth_calculator) do |f| %>
    <% if @growth_calculator.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@growth_calculator.errors.count, "error") %> prohibited this growth_calculator from being
            saved:</h2>

          <ul>
            <% @growth_calculator.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :starting_population %><br>
      <%= f.number_field :starting_population %>
    </div>
    <div class="field">
      <%= f.label :growth_rate %><br>
      <%= f.text_field :growth_rate %>
    </div>
    <div class="field">
      <%= f.label :time_frame %><br>
      <%= f.number_field :time_frame %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>
<!-- Table will be inserted here -->
<div id="growth-table" class="table-format"></div>

app/views/growth_calculators/_population_table.erb
<table class="CSSTableGenerator" width="30%">
  <th>Year</th>
  <th>Population</th>
  <% @population_array.each_with_index do |p,n|  %>
    <tr>
      <td><%= n %></td>
      <td><%= p.round(2) %></td>
    </tr>
  <% end %>

</table>

app/views/growth_calculators/edit.html.erb
<h1>Editing Growth Calculator</h1>

<%= render 'form' %>

<%= link_to 'Show', @growth_calculator %> |
<%= link_to 'Back', growth_calculators_path %>

app/views/growth_calculators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Growth Calculators</h1>

<table>
  <thead>
    <tr>
      <th>Starting population</th>
      <th>Birth rate</th>
      <th>Time frame</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @growth_calculators.each do |growth_calculator| %>
      <tr>
        <td><%= growth_calculator.starting_population %></td>
        <td><%= growth_calculator.growth_rate %></td>
        <td><%= growth_calculator.time_frame %></td>
        <td><%= link_to 'Show', growth_calculator %></td>
        <td><%= link_to 'Edit', edit_growth_calculator_path(growth_calculator) %></td>
        <td><%= link_to 'Destroy', growth_calculator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Growth calculator', new_growth_calculator_path %>

app/views/growth_calculators/new.html.erb
<h1>New Growth Calculator</h1>

<%= render 'form' %>

<%= link_to 'Back', growth_calculators_path %>

app/views/growth_calculators/population.js.erb
$('#growth-table').html("<%= j (render 'population_table') %>")

app/views/growth_calculators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starting population:</strong>
  <%= @growth_calculator.starting_population %>
</p>

<p>
  <strong>Birth rate:</strong>
  <%= @growth_calculator.growth_rate %>
</p>

<p>
  <strong>Time frame:</strong>
  <%= @growth_calculator.time_frame %>
</p>

<%= render 'population_table' %>

<%= link_to 'Edit', edit_growth_calculator_path(@growth_calculator) %> |
<%= link_to 'Back', growth_calculators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cis4339</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>